import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Dhruvin",
    lastName: "Mehta",
    username: "dhruvin.mehta25799@gmail.com",
    password: "1234567890",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Maharshi",
    lastName: "Maniar",
    username: "maharshi.maniar@gmail.com",
    password: "thisissocialmedia",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Manan",
    lastName: "Jain",
    username: "manan.jain@gmail.com",
    password: "mynameispasha",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Mahimn",
    lastName: "Dhiver",
    username: "mahimn.dhiver@gmail.com",
    password: "REACTionsIsBest",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Jack",
    lastName: "Sparrow",
    username: "jack.sparrow@pirates.com",
    password: "whereIsTheTreasure",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Tony",
    lastName: "Stark",
    username: "tony.stark@avengers.com",
    password: "IAmIronMan",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Naruto",
    lastName: "Uzumaki",
    username: "naruto.uzumaki@hokage.com",
    password: "INeverGiveUp",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Jennie",
    lastName: "Kim",
    username: "jennie.kim@blackpink.com",
    password: "BlackpinkIsTheBest",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Gojo",
    lastName: "Satoru",
    username: "gojo.satoru@jujutsu.com",
    password: "IAmTheStrongest",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Light",
    lastName: "Yagami",
    username: "light.yagami@shinigami.com",
    password: "ShinigamiLoveApples",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Barry",
    lastName: "Allen",
    username: "barry.allen@starlabs.com",
    password: "IAmTheFastestManAlive",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Harley",
    lastName: "Quinn",
    username: "harley.quinn@gotham.com",
    password: "WhereIsJoker",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Test",
    lastName: "User",
    username: "test.user@gmail.com",
    password: "1234567890",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
